name: Cronut Test

on: [push]

env: # runner has 7g of ram
  JVM_OPTS: -Xmx6G

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java11
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 'latest'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deps
        working-directory: ./
        run: lein with-profile +smoke deps

      - name: Fmt
        working-directory: ./
        run: lein fmt

      - name: Kondo
        working-directory: ./
        run: lein kondo

      - name: Test
        working-directory: ./
        run: lein test

      - name: NVD
        uses: dependency-check/Dependency-Check_Action@main
        env:
          # actions/setup-java changes JAVA_HOME so it needs to be reset to match the depcheck image
          JAVA_HOME: /opt/jdk
        with:
          project: cronut 
          path: target
          format: 'HTML'
          out: reports
          args: >
            --suppression ./dependency-check-suppressions.xml

      - name: Persist NVD
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nvd-cronut-${{ github.sha }}
          path: reports/*
          retention-days: 1
